disabled_rules:
- trailing_whitespace

opt_in_rules:
- empty_count
- yoda_condition
- closure_body_length
- closure_end_indentation
- closure_spacing
- comma_inheritance
- conditional_returns_on_newline
- contains_over_filter_count
- contains_over_filter_is_empty
- contains_over_first_not_nil
- contains_over_range_nil_comparison
- convenience_type
- direct_return
- discouraged_none_name
- discouraged_object_literal
- discouraged_optional_boolean
- discouraged_optional_collection
- empty_collection_literal
- empty_string
- empty_xctest_method
- enum_case_associated_values_count
- number_separator
- object_literal
- one_declaration_per_file
- operator_usage_whitespace
- optional_enum_case_matching
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
- period_spacing
- prefer_key_path
- prefer_self_in_static_references
- unused_parameter
- anonymous_argument_in_multiline_closure
- array_init
- attributes
- file_header
- file_name
- file_name_no_space
- modifier_order

analyzer_rules:
  - explicit_self
  - capture_variable
  - typesafe_array_init
  - unused_declaration
  - unused_import
